### PR TITLE
Multi image upload

### PR DESCRIPTION
**Pull request by ajaxtown**
#### Requirements:
- Insert multiple images during file upload for Posts and Pages (this will not work if you try to add exisitng images from media gallery).
- Featured image upload should be single.
- Uploading avatar and hero banner should be single.

### CODE REVIEW

**Comment by ajaxtown** [comment]
@alder could you please test this branch.

**Comment by alder** [comment]
@ajaxtown sure. I'll do it now.

**Comment by alder** [comment]
@ajaxtown 
1. Inserting new images to post/page - :ok: 
2. Avatar/featured image is single - :ok: 

**Issues:**
1. When user insert new images to post/page - these images doesn't added to Media.
2. When user try to upload multiple images directly on Media page only one image added with broken src:
```http://localhost:4040/uploads/1529865819996.jpg,/uploads/1529865820039.jpg,/uploads/1529865820061.jpg,/uploads/1529865820073.jpg,/uploads/1529865820104.jpg```

**Comment by ajaxtown** [comment]
Thanks @alder .. I made the necessary changes according to your feedback.

**Pull request merged**
