### PR TITLE
Fixed tags and categories in posts

### PR DESCRIPTION
**Pull request by ajaxtown**
A fix for https://github.com/letterpad/letterpad/issues/53

### CODE REVIEW

**Comment by alder** [comment]
@ajaxtown GraphQL error when trying to save/create post:
`[0] { GraphQLError: Variable "$taxonomies" got invalid value [{"id":4,"name":"sports","type":"post_tag","slug":"sports","text":"sports"},{"id":5,"name":"nature","type":"post_tag","slug":"nature","text":"nature"},{"id":6,"name":"street","type":"post_tag","slug":"street","text":"street"},{"id":2,"name":"Nature","type":"post_category","slug":"nature","text":"Nature"}].
[0] In element #0: In field "text": Unknown field.
[0] In element #1: In field "text": Unknown field.
[0] In element #2: In field "text": Unknown field.
[0] In element #3: In field "text": Unknown field.`

**Comment by ajaxtown** [comment]
I will fix this tonight.

**Comment by ajaxtown** [comment]
@alder this is ready to test.

**Comment by alder** [comment]
@ajaxtown previous issue was fixed, but we have new one

1. Edit post
2. Add more than 1 **new** tags to post. For example: tag1, tag2
3. Update the post

Server raises an error:
```
[[0] { SequelizeTimeoutError: SQLITE_BUSY: database is locked
[0]     at Query.formatError (/home/alder/Work/src/letterpad/node_modules/sequelize/lib/dialects/sqlite/query.js:415:16)
[0]     at Statement.afterExecute (/home/alder/Work/src/letterpad/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
[0]     at Statement.replacement (/home/alder/Work/src/letterpad/node_modules/sqlite3/lib/trace.js:19:31)
[0]   name: 'SequelizeTimeoutError',
[0]   parent:
[0]    { Error: SQLITE_BUSY: database is locked
[0]      errno: 5,
[0]      code: 'SQLITE_BUSY',
[0]      sql:
[0]       'INSERT INTO `taxonomy` (`id`,`name`,`type`,`created_at`,`updated_at`) VALUES (NULL,\'tag2\',\'post_tag\',\'2018-07-01 11:58:15.205 +00:00\',\'2018-07-01 11:58:15.205 +00:00\');' },
[0]   original:
[0]    { Error: SQLITE_BUSY: database is locked
[0]      errno: 5,
[0]      code: 'SQLITE_BUSY',
[0]      sql:
[0]       'INSERT INTO `taxonomy` (`id`,`name`,`type`,`created_at`,`updated_at`) VALUES (NULL,\'tag2\',\'post_tag\',\'2018-07-01 11:58:15.205 +00:00\',\'2018-07-01 11:58:15.205 +00:00\');' },
[0]   sql:
[0]    'INSERT INTO `taxonomy` (`id`,`name`,`type`,`created_at`,`updated_at`) VALUES (NULL,\'tag2\',\'post_tag\',\'2018-07-01 11:58:15.205 +00:00\',\'2018-07-01 11:58:15.205 +00:00\');' }
[0] { Error: Resolve function for "Response.post" returned undefined
[0]     at /home/alder/Work/src/letterpad/node_modules/graphql-tools/src/schemaGenerator.ts:476:13
[0]     at resolveOrError (/home/alder/Work/src/letterpad/node_modules/graphql/execution/execute.js:474:12)
[0]     at resolveField (/home/alder/Work/src/letterpad/node_modules/graphql/execution/execute.js:460:16)
[0]     at /home/alder/Work/src/letterpad/node_modules/graphql/execution/execute.js:275:18
[0]     at Array.reduce (<anonymous>)
[0]     at executeFields (/home/alder/Work/src/letterpad/node_modules/graphql/execution/execute.js:272:42)
[0]     at collectAndExecuteSubfields (/home/alder/Work/src/letterpad/node_modules/graphql/execution/execute.js:722:10)
[0]     at completeObjectValue (/home/alder/Work/src/letterpad/node_modules/graphql/execution/execute.js:704:10)
[0]     at completeValue (/home/alder/Work/src/letterpad/node_modules/graphql/execution/execute.js:601:12)
[0]     at completeValue (/home/alder/Work/src/letterpad/node_modules/graphql/execution/execute.js:570:21)
[0]     at /home/alder/Work/src/letterpad/node_modules/graphql/execution/execute.js:558:14
[0]   message: 'Resolve function for "Response.post" returned undefined',
[0]   locations: [ { line: 9, column: 5 } ],
[0]   path: [ 'updatePost', 'post' ] }]
```
And only 1 of 2 tags saved.

**Comment by ajaxtown** [comment]
Thanks @alder. this should be fixed now.

**Comment by alder** [comment]
@ajaxtown issue fixed. PR can be merged.

**Pull request merged**
